---
title: "R Notebook"
output: html_notebook
---

```{r}
library(hexSticker)
library(showtext)
## Loading Google fonts (http://www.google.com/fonts)
font_add_google("Public Sans", regular.wt = 400)
## Automatically use showtext to render text for future devices
showtext_auto()
```

```{r}
imgurl <- system.file("assets/barbecue.svg", package = "dewey")
sticker(imgurl, 
        s_x = 1,
        s_y = 1,
        s_width = .7,
        s_height = .7,
        package = "dewey",
        p_x = .7,
        p_y = 1.4,
        p_color = "white",
        p_size = 62,
        p_family = "Public Sans",
        h_fill = "#532d8e",
        h_color = "#B1B3B5",
        dpi = 1200,
        filename = "assets/sticker.png")

sticker(imgurl, 
        s_x = 1,
        s_y = 1,
        s_width = .7,
        s_height = .7,
        package = "dewey",
        p_x = .7,
        p_y = 1.4,
        p_color = "white",
        p_size = 5,
        p_family = "Public Sans",
        h_fill = "#532d8e",
        h_color = "#B1B3B5",
        dpi = 1200,
        filename = "assets/sticker.svg")
```

